### ISSUE TITLE
analysis.exe core dumps on some WAV files

### ISSUE THREAD

**Issue by mhuckvale** [mmorise/World#18]
Dear Masanori

Compiled latest version with CYGWIN on Windows using given Makefile
Running over all the hurricane/news audio files (16kHz sampling rate), analysis crashes on a handful of files including this one (100_1.wav).
It seems to be a memory corruption somewhere in D4C, but tricky to track down.

[100_1.zip](https://github.com/mmorise/World/files/679972/100_1.zip)

Thanks for your work on WORLD - it's great otherwise!

Mark

**Comment by mmorise** [comment]
Thank you for your report.

I checked the source code in D4C.cpp and found several doubtful points.
Since a safeguard was added to the source code, I believe your concern was resolved.
(Actually, my environment (Cygwin on Win 10) was not able to cause this error.)

If the error is still caused, please contact me again.

Please note: arguments in InitializeCheapTrickOption() has changed. Please see test.cpp.

**Comment by truongdo** [comment]
I confirm that it still happens on ubuntu 14.04 g++ 4.8.5.
analysis 100_1.wav out.f0 out.sp out.ap

Below is the output,
File information
Sampling : 16000 Hz 16 Bit
Length 52861 [sample]
Length 3.30381[sec]

Analysis
DIO: 56 [msec]
StoneMask: 41 [msec]

Program received signal SIGSEGV, Segmentation fault.
0x000000000040f226 in interp1Q ()
(gdb) bt
#0  0x000000000040f226 in interp1Q ()
#1  0x0000000000403136 in DCCorrection ()
#2  0x0000000000402aec in CheapTrick ()
#3  0x000000000040177f in main ()

**Comment by mmorise** [comment]
OK. I was able to expect the cause of the error.
Please wait an hour, and I will debug this problem.

**Comment by mmorise** [comment]
I updated the DCCorrection() in common.cpp.
There was an error in Segmentation fault, so I fixed it.
Was the problem resolved?

**Comment by truongdo** [comment]
It still failed, but now in different place,

Program received signal SIGSEGV, Segmentation fault.
0x0000000000402fd6 in InitializeCheapTrickOption ()
(gdb) bt
#0  0x0000000000402fd6 in InitializeCheapTrickOption ()
#1  0x0000000000401694 in main ()

**Comment by mmorise** [comment]
The cause may be InitializeCheapTrickOption() because its arguments have changed.
I updated analysis.cpp. Please re-compile and test it.

**Comment by truongdo** [comment]
great! no more error now. But I don't know if @mhuckvale  still have the problem because I'm testing it on linux (not CYGWIN)

**Comment by mmorise** [comment]
Thank you very much for your cooperation!
I wait next comment from @mhuckvale.

**Comment by mhuckvale** [comment]
I have only tested with the one WAV file, but the analysis example doesn't crash on CYGWIN now.
I will run it on all the WAV files in the hurricane corpus next.
Thanks
Mark

**Comment by mhuckvale** [comment]
It now runs on the first 1000 files of hurricane/news - thanks!
Mark
