### ISSUE TITLE
crash issues at CheapTrick function 

### ISSUE THREAD

**Issue by szhaomsft** [mmorise/World#19]
it crash on windows for one wave file. 
potentially some buffer overrun issue

there seems no gurantee that waveform is not overrun in this code GetWindowedWaveform
  double *waveform = forward_real_fft->waveform;
  for (int i = 0; i <= half_window_length * 2; ++i)
    waveform[i] = x[safe_index[i]] * window[i] + randn() * 0.000000000000001;

**Comment by mmorise** [comment]
Thank you for your contact.

If possible, please give me the speech file.
I will debug the problem with the file.

The parameter "safe_index" is the parameter for guarding the sequence from the buffer overrun.
I think that this parameter cannot work as expected.

**Comment by szhaomsft** [comment]
this is the repro wav https://github.com/szhaomsft/misc/blob/master/1000000001.wav

**Comment by szhaomsft** [comment]
for some reason, it crased on the demo wav to me today. 

C:\github\World\visualstudio\x86\Debug\win.exe vaiueo2d.wav o.wav 1 1

crash line 


static double GetCurrentVUV(int current_location, WorldSynthesizer *synth) {
  double current_vuv = 0.0;
  int pointer = synth->current_pointer % synth->number_of_pointers;

  int start_sample =
    static_cast<int>(ceil((synth->f0_origin[pointer] - 1) *
    synth->frame_period * synth->fs));

  **current_vuv =
    synth->interpolated_vuv[pointer][current_location - start_sample + 1];
  return current_vuv;**
}

**Comment by mmorise** [comment]
First problem was fixed, it was the problem in determining the parameter f0_floor in CheapTrick().
On the other hand, I could not replicate the error in your second comment.
Did you set a special option for compile? I checked the program in Debug (x86) that is the same condition.

**Comment by szhaomsft** [comment]
@mmorise  thanks for you fix. it fixed the 1st problem.

however,  the second one still failed to me.  
I found it is because I use appverify to add basic check for win.exe 
https://www.microsoft.com/en-us/download/details.aspx?id=20028

install it,  run appverif in command line ,  add win.exe into applications,  save,  then 

run win.exe 1000000001.wav o.wav 1 1

you will see it crash

**Comment by mmorise** [comment]
Thank you for giving information.

I confirmed the error.
But it may take some to solve this problem because I don't know something about this error.
Since I have also several deadlines, please give me a time.

**Comment by mmorise** [comment]
The bug in second problem was fixed.
However, I still have a concern because I checked the program in several speech files only.
